[package]
name = "httped"
version = "0.1.0"
edition = "2024"
description = "An HTTP request and response testing service"
repository = "https://github.com/Bing-su/httped"

[dependencies]
async-stream = "0.3"
bytes = "1"
clap = { version = "4", features = ["derive", "env", "unicode", "wrap_help"] }
data-encoding = "2"
percent-encoding = "2"
rand = { version = "0.10", features = ["chacha"] }
regex = "1"
rust-embed = {
  version = "8",
  features = ["compression", "deterministic-timestamps"]
}
salvo = {
  version = "0.95",
  features = [
    "basic-auth",
    "compression",
    "logging",
    "oapi",
    "serve-static",
    "sse",
    "timeout",
    "trailing-slash",
    "websocket",
  ]
}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
ulid = "3"
uuid = { version = "1", features = ["v4", "v7"] }

[dev-dependencies]
futures-util = "0.3"
rstest = "0.26"
tokio-tungstenite = "0.30"

[profile.release]
strip = true
lto = true
codegen-units = 1
