[package]
name = "httped"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
async-stream = "0.3"
bytes = "1"
clap = { version = "4", features = ["derive", "env", "unicode", "wrap_help"] }
data-encoding = "2"
regex = "1"
rust-embed = {
  version = "8",
  features = ["compression", "deterministic-timestamps"]
}
salvo = {
  version = "0.94",
  features = [
    "anyhow",
    "basic-auth",
    "compression",
    "logging",
    "oapi",
    "serve-static",
    "sse",
    "trailing-slash",
    "websocket",
  ]
}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
futures-util = "0.3"
rstest = "0.26"
tokio-tungstenite = "0.30"

[profile.release]
strip = true
lto = true
codegen-units = 1
